spring:
  application:
    name: eat-ssu-kotlin

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL

  jpa:
    hibernate:
      ddl-auto: create-drop # create-drop, update, validate, none
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        show_sql: true # SQL 출력
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  secretKey: 58244814c55d300622bf0c14b398221f783ed70440df53f001e4366683b9ee26a532652096d0acce7c8b01929dd0b49305442f3f18039e30781898befdc5696b
  token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 259200

springdoc:
  swagger-ui:
    # Swagger UI 페이지에 대한 경로
    path: /swagger-ui.html
    # Group 별 정렬 기준 (ASC 오름차순, DESC 내림차순)
    groups-order: DESC
    # API 목록 내 정렬 기준 (method, alpha)
    operationsSorter: method
    # Swagger UI가 로드될 때 기본적으로 제공하는 예제 URL 생략
    disable-swagger-default-url: true
    # API 요청 시 실행 시간을 표시
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**
