spring:
  application:
    name: eat-ssu-kotlin

  config:
    import: "optional:classpath:secrets.yml"

  cache:
    jcache:
      config: "classpath:ehcache.xml"

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
jwt:
  secretKey: 58244814c55d300622bf0c14b398221f783ed70440df53f001e4366683b9ee26a532652096d0acce7c8b01929dd0b49305442f3f18039e30781898befdc5696b
  token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 259200

cloud:
  aws:
    credentials:
      accessKey: ${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
      secretKey: ${CLOUD_AWS_CREDENTIALS_SECRETKEY}
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
    region:
      static: ${CLOUD_AWS_REGION_STATIC}
    stack:
      auto: ${CLOUD_AWS_STACK_AUTO}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**

slack:
  token: ${SLACK_TOKEN}
